### PR TITLE
Fixed permissions of shell scripts in binary builds

### PR DESCRIPTION
**Pull request by tommaso-borgato**
In binary builds from sources, when the source is an already provisioned server (e.g. some "target/server" produced by the `wildfly-maven-plugin`), then execution permissions on ".sh" files are lost;

This causes the following error when the POD starts:

```
/opt/jboss/container/wildfly/run/run: line 74: /opt/server/bin/openshift-launch.sh: Permission denied
```

This MR just fixes permissions on ".sh" files which is the bare minimum required to have a working server installation;

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [ ] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by mnovak1** [comment]
@tommaso-borgato I don't understand the details here, I just want to make sure that this is not workaround for something what is actually a bug. Shouldn't `wildfly-maven-plugin` preserve permission on `.sh` files?

**Comment by mnovak1** [comment]
Or is the executable flag lost when creating tar?

**Comment by tommaso-borgato** [comment]
@mnovak1 I am not an XTF expert, but I experienced the same issue on another project.... IIUC the java api used to assemble the tar (`TarArchiveEntry`) have issues with preserving permissions.... for our use case the fix I submitted is enough

**Comment by fabiobrz** [comment]
> @mnovak1 the issue here is that classes in `org.apache.commons.compress.archivers.tar` e.g. `TarArchiveEntry` do not preserve permissions when building a `tar` .... this is actually a bug in `xtf`
> 
> it's no surprise to me that the issue is in the only step of the process which is using Java library for creating a `tar` because I experienced the very same issue on another project (the solution was running `zip` directly there - which we cannot apply here)
> 
> this MR is a workaround for the one scenario that we use: creating a tar stream containing a server directory to be sent to the builder image
> 
> a more comprehensive solution would be try and find and alternative to `org.apache.commons.compress.archivers.tar` which preserves permissions (if any) and re-write `BinaryBuildFromSources`
> 
> perhaps we might trace the more comprehensive solution in a separate issue (with lower priority smile )

From what I can read around, this might be intentional, since permissions are dealt with at the OS level.
In such a case, it seems to me this is not a workaround for an external component bug, but rather a proper fix for the XTF (caller) behavior when dealing with org.apache.commons.compress.archivers.tar.TarArchiveEntry etc.

In such a case there's no issue that should be created externally, maybe an internal one fixed by this very PR.
Let me know in case I am missing something.

**Comment by tommaso-borgato** [comment]
@mnovak1 good idea, going to check

**Comment by mnovak1** [comment]
> @mnovak1 good idea, going to check

:+1: ...thanks for looking at it.

**Comment by tommaso-borgato** [comment]
@mnovak1 I applied your suggestion and the bug fix is now complete

**Review by fabiobrz — APPROVED** [review]
I am approving since this LGTM now. But leaving the last word to @mnovak1 of course :)


Maybe this could be extracted into some utils in the future and maybe we could add a comment identifying the source for such conversion.

**Review by mnovak1 — APPROVED** [review]

**Comment by mnovak1** [comment]
LGTM, merging. Thanks @tommaso-borgato !

**Pull request merged**
