### PR TITLE
Downgrade impsort plugin to JDK 8 compatible version

### PR DESCRIPTION
**Pull request by mnovak1**
Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by simkam** [comment]
So we are dropping support for JDK 8?

**Comment by mnovak1** [comment]
> So we are dropping support for JDK 8?

Nope. This is to unblock this check in GH action. All artificts has still compile target to JDK 8.

**Comment by simkam** [comment]
```
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
```
isn't enough. We should then switch to using `--release` - https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html

**Comment by mnovak1** [comment]
> ```
>                 <configuration>
>                     <source>${maven.compiler.source}</source>
>                     <target>${maven.compiler.target}</target>
>                 </configuration>
> ```
> 
> isn't enough. We should then switch to using `--release` - https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html

I'm not sure I understand. Could you elaborate more, please?

**Comment by simkam** [comment]
Unlike `source` and `target`, `release` ensures that only bytecode usable by the selected version is produced by the build. More details for example in https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/ .

**Comment by mnovak1** [comment]
Thanks. I've updated the compiler plugin to set release version as well.

**Comment by mnovak1** [comment]
@simkam I've lowered version of impsort plugin to be JDK 8 compatible. However it's just temporary solution. I would like to migrate to Spotless in near future.

**Comment by simkam** [comment]
ok, but please update commit message and PR description

**Comment by mnovak1** [comment]
done

**Pull request merged**
