### PR TITLE
Added Oracle FREE DB

### PR DESCRIPTION
**Pull request by liborfuka**
Please make sure your PR meets the following requirements:
- [ ] Pull Request contains a description of the changes
- [ ] Pull Request does not include fixes for multiple issues/topics
- [ ] Code is formatted, imports ordered, code compiles and tests are passing
- [ ] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by OndrejGerzicak** [comment]
I don't get purpose of this OracleFREE builder? There is already OracleXE builder. The only difference I can see between those two is the default DB_NAME, but that should be possible to set with a parameter in constructor. If the constructor isn't enough for you feel free to add another that suits you, but I don't think it necessary to create a new class in this case. Am I missing something?

**Comment by liborfuka** [comment]
There are two differences - DATA_DIR and DB_NAME. Yes It should be solved by adding new constructor but there are two different products:
[Oracle Database Express Edition](https://container-registry.oracle.com/ords/f?p=113:4:7483808239366:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=3JAJtiPP9_kd7eDpBDZ3zp6hgUlErmUiB5mMB07PUCMOPWCYk79V5zPpHc26Jc0vSwQn5FIol2D3_83ysIYfPlQ) (our class OracleXE)
[Oracle Database Free](https://container-registry.oracle.com/ords/f?p=113:4:7483808239366:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:1863,1863,Oracle%20Database%20Free,Oracle%20Database%20Free,1,0&cs=3HxsYknVPCeKS8tahJFS2_gfaae4zXuTV32uxzBXIGSQXJ94wsyd0KpqysVUxWQRPujcnfq8dMzatn04tFOM-JQ)

Ok, how to finally solve it?
Create new constructor in OracleXE class?

**Comment by OndrejGerzicak** [comment]
Ok missed the DATA_DIR, sorry for that. As it's two different product maybe you are right that there should be separate classes. But to avoid the code duplicity, you could create some base Oracle DB class and inherit the common code for the product explicit classes from there?

**Comment by liborfuka** [comment]
Ok, I will create AbstractOracle class.

**Comment by liborfuka** [comment]
I added OracleAbstract class. DATA_DIR /opt/oracle/oradata is the same in the latest Oracle DB images: container-registry.oracle.com/database/express:latest and container-registry.oracle.com/database/free:latest

**Review by OndrejGerzicak — APPROVED** [review]
LGTM! Thank you

**Review by mnovak1 — APPROVED** [review]

**Comment by mnovak1** [comment]
LGTM, merging.

**Comment by mnovak1** [comment]
I've found that changing DATA_DIR to `/opt/oracle/oradata` starting of Oracle takes significatly longer (from seconds to 10+ minutes). I'll return it back to `/var/lib/oracle/data`. @liborfuka  could you check what this change will do with Oracle FREE DB?

**Pull request merged**
