### PR TITLE
Update GH Actions to check that code is well formatted in PR check an…

### PR DESCRIPTION
**Pull request by mnovak1**
…d during new release

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by mnovak1** [comment]
This is follow-up on https://github.com/xtf-cz/xtf/pull/394

**Comment by mnovak1** [comment]
@Crumby could you review it as well, please?

**Comment by mnovak1** [comment]
@pkremens could you review it, please? I did similar change into Appsint so I believe you know what's going on. :-)

**Comment by pkremens** [comment]
Well I can see the same "problem" as we had with Appsint - users are no longer able to build the (from) sub-module directories

```
[pkremens@localhost core] $ mvn compile
...
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.11.0:format (default) on project core: Cannot find config file [/home/pkremens/devel/openshift/xtf/core/ide-config/eclipse-format.xml] -> [Help 1]
```

but this might not be a problem at all for XTF.

Maybe we should consider releasing a more general `ide-config` artifact which could be shared by all products - same way we did in Appsint.

**Comment by mnovak1** [comment]
@pkremens I'll change it as part of issue: https://github.com/xtf-cz/xtf/issues/400 once someone starts to complain of it. I think this PR is ok for XTF now.

**Pull request merged**
