### PR TITLE
enable failFast for Openshift deploy

### LINKED ISSUE #337: Improve logging for errors during images building
If TS fails in image building, I see currently something like this:
```
[2019-11-01 09:50:24,695] WARN - Build HA_SERVLET_COUNTER failed!
```

But I expect ERROR log level and more informations about this, for example:
* no image found in manifest list for architecture s390x, OS linux
* x509: certificate signed by unknown authority
* etc.

### PR DESCRIPTION
**Pull request by laDok8**
Please make sure your PR meets the following requirements:
- [ ] Pull Request contains a description of the changes
- [ ] Pull Request does not include fixes for multiple issues/topics
- [ ] Code is formatted, imports ordered, code compiles and tests are passing
- [ ] Code is self-descriptive and/or documented

this PR resolves #337
It appears that no changes for `ManagedBuildPrebuilder` are necessary

### CODE REVIEW

**Review by mnovak1 — APPROVED** [review]
@laDok8 LGTM, do you have a CI run?

**Comment by laDok8** [comment]
@mnovak1  pipeline seems to be unstable atm, this is the best I could do:
https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/69/
https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/67/

**Comment by mnovak1** [comment]
> @mnovak1 pipeline seems to be unstable atm, this is the best I could do: https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/69/ https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/67/

@laDok8 could you link some comparison runs without this change as well?

**Comment by laDok8** [comment]
@mnovak1 here are updated runs:
master: https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/85/
PR: https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/84/

**Review by mnovak1 — APPROVED** [review]
Thanks, merging.

**Pull request merged**
