### PR TITLE
Ability to supress logging STD Err in OpenShiftBinary

### PR DESCRIPTION
**Pull request by istraka**
Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by mchoma** [comment]
I wonder when is this useful? We normally want maximum information available when investigating issues.

**Comment by pkremens** [comment]
@mchoma see https://trello.com/c/bBuVKC6R/67-todo-get-rid-of-operator-error-log-messages-during-subscription

**Comment by pkremens** [comment]
Although I can now see, that there is also a `--ignore-not-found` switch which could help here.

**Comment by mnovak1** [comment]
I have no problem to merge it as it does not change default however let me know whether you still want it.

Also looks like that XTF CI is stuck again...hell.

**Pull request closed without merging**
