### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by mnovak1**
Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Comment by mnovak1** [comment]
@LittleJohnII I did testing with EAP Openshift test suite and did not get any regression. I had to only exclude some transitive dependencies to sort some version conflicts with Jackson.

**Comment by LittleJohnII** [comment]
I'm fine with merging this from the perspective of EAP QE. Didn't you say you had to add some excludes into the OpenShift test suite though? I think we should also let other teams know about this: Cc @Crumby @dsimansk @mocenas (latest contributors).

If there are no complaints by tomorrow, I'll merge it.

**Review by LittleJohnII — APPROVED** [review]

**Review by Crumby — APPROVED** [review]

**Comment by mnovak1** [comment]
>... Didn't you say you had to add some excludes into the OpenShift test suite though? I think we should also let other teams know about this: Cc @Crumby @dsimansk @mocenas (latest contributors).

+1, I'll start to provide those notes into https://github.com/xtf-cz/xtf/releases

**Comment by LittleJohnII** [comment]
Merging.

**Pull request merged**
