### PR TITLE
Refactor OpenShift:clean to delete resources via list

### PR DESCRIPTION
**Pull request by dsimansk**
Good old times are coming back...

### CODE REVIEW

**Comment by mchoma** [comment]
Won't that introduce `WaiterException: Cleaning project `?

**Comment by dsimansk** [comment]
I brought back "safety net" code. From my limited test executions the performance degradation is gone and I didn't see leftovers warning either. 
Performance issue is definitely caused by different handling of list vs. single resource deletion. I'll try to collect more data tomorrow.

**Comment by dsimansk** [comment]
@Crumby would you mind merging this PR and trying it out in the wild? 

After a brief discussion with @maschmid, the fallback plan will be to implement `clean()` through plain http calls with the same `DeleteOptions` etc. as `oc delete all --all`.

**Comment by mchoma** [comment]
@dsimansk  Could we have release with that change in place? Running our testsuite we do not see `WaiterException: Cleaning project` anymore and performance is ~ same.

**Pull request merged**
