### PR TITLE
Client upgrade + clean refactor

### PR DESCRIPTION
**Pull request by dsimansk**
I've removed the "hack" and leveraged new method to specify propagation policy. However, one drawback is that I haven't found a way to set both `gracePeriod` and `propagationPolicy`. So far I haven't spotted any issues though.

### CODE REVIEW

**Comment by mchoma** [comment]
I hit `WaiterException: Cleaning project` with this in place

**Comment by dsimansk** [comment]
@mchoma with client version `4.6.0`? Were there dangling pods, or other resources?

**Comment by mchoma** [comment]
@dsimansk yes, `4.6.0`. I run 0.14-SNAPSHOT which contains this version. We do not override client version in our project anymore.

I guess it was pod (`elytron-simple-1-sm5zs`). But I am not sure. I would need to investigate deeper next time it occurres.  I am running test run again...

**Comment by mchoma** [comment]
@dsimansk I have hit the pod ```apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: eap-app-migration
    openshift.io/deployment.name: eap-app-migration-1
    openshift.io/scc: restricted
  creationTimestamp: '2019-09-24T07:45:30Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2019-09-24T07:49:53Z'
  finalizers:
    - orphan
  generateName: eap-app-migration-1-
  labels:
    application: eap-app
    deployment: eap-app-migration-1
    deploymentConfig: eap-app-migration
    deploymentconfig: eap-app-migration
  name: eap-app-migration-1-jbz7b
  namespace: eap72-tests-13-mx
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: eap-app-migration-1
      uid: 46ea4e82-de9f-11e9-b23d-fa163e9a0fb6
  resourceVersion: '8430399'
  selfLink: /api/v1/namespaces/eap72-tests-13-mx/pods/eap-app-migration-1-jbz7b
  uid: 487826d4-de9f-11e9-b23d-fa163e9a0fb6```

**Pull request merged**
