### PR TITLE
Set Oracle data dir back to /var/lib/oracle/data from /opt/oracle/ora…

### PR DESCRIPTION
**Pull request by mnovak1**
…data to speed up Oracle DB start.

@liborfuka fyi I've tried Oracle FREE and started significantly faster as well. So this should work for both Oracle FREE and Oracle XE.

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

**Review by simkam — APPROVED** [review]

**Comment by liborfuka** [comment]
Hi @mnovak1

Oracle data files are stored in /opt/oracle/oradata in Oracle DB images. If you change it to something else it starts faster but you can not test with physical volume claims and you can not test these test scenarios.

**Comment by mnovak1** [comment]
> Hi @mnovak1
> 
> Oracle data files are stored in /opt/oracle/oradata in Oracle DB images. If you change it to something else it starts faster but you can not test with physical volume claims and you can not test these test scenarios.

Is it actually needed for the purpose of testing where we don't care about DB data to survive the test?

**Comment by liborfuka** [comment]
I have test scenario where I restart DB in the middle of test and test if Spring Boot app reconnect to DB successfully.

**Comment by mnovak1** [comment]
@liborfuka  Thanks, merged.

**Pull request merged**
